name: "JFrog Upload Action"
description: "Upload dummy artifact to JFrog Artifactory"
inputs:
  jfrog-url:
    description: "JFrog Artifactory URL"
    required: true
  jfrog-username:
    description: "JFrog username"
    required: true
  jfrog-key:
    description: "JFrog password or API key"
    required: true
  repo:
    description: "Target repository in Artifactory"
    required: true
  file:
    description: "File to upload"
    required: true
  target-path:
    description: "Path in Artifactory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI
      shell: bash
      run: |
        curl -fL https://getcli.jfrog.io | sh
        sudo mv jfrog /usr/local/bin/

    - name: Configure JFrog CLI
      shell: bash
      run: |
        jfrog config add my-server \
          --artifactory-url "${{ inputs.jfrog-url }}" \
          --user "${{ inputs.jfrog-username }}" \
          --apikey "${{ inputs.jfrog-key }}" \
          --interactive=false
        OUTPUT=$(jfrog rt ping)
        echo "jfrog connection status ==> $OUTPUT"
        jfrog c show
    
    - name: Verify JFrog Connection
      shell: bash
      run: |
        echo "🔍 Checking JFrog server connectivity..."
        jfrog rt ping --server-id=my-server
        echo "📜 Showing JFrog configuration..."
        jfrog c show my-server
    
    - name: Upload Artifact
      shell: bash
      run: |
        jfrog rt u "${{ inputs.file }}" "{{ inputs.target-path }}"
