name: "jfrog Upload Action"
description: "Upload dummy artifact to jfrog Artifactory"
inputs:
  jfrog-url:
    description: "jfrog Artifactory URL"
    required: true
  jfrog-username:
    description: "jfrog username"
    required: true
  jfrog-key:
    description: "jfrog password or API key"
    required: true
  repo:
    description: "Target repository in Artifactory"
    required: true
  file:
    description: "File to upload"
    required: true
  target-path:
    description: "Path in Artifactory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup jfrog CLI
      shell: bash
      run: |
        curl -fL https://getcli.jfrog.io | sh
        sudo mv jfrog /usr/local/bin/

    - name: Configure jfrog CLI
      shell: bash
      run: |
        echo "🔑 Configuring jfrog CLI..."
        jf config add my-server \
          --artifactory-url "${{ inputs.jfrog-url }}" \
          --user "${{ inputs.jfrog-username }}" \
          --apikey "${{ inputs.jfrog-password }}" \
          --interactive=false \
          --overwrite \
          --enc-password=false

   
    - name: Verify jfrog Connection
      shell: bash
      run: |
        echo "🔍 Checking jfrog server connectivity..."
        jf rt ping --server-id=my-server
        echo "📜 Showing jfrog configuration..."
        jf config show my-server
    
    - name: Upload Artifact
      shell: bash
      run: |
        jf rt u "${{ inputs.file }}" "{{ inputs.target-path }}"
