name: "JFrog Upload Action"
description: "Upload dummy artifact to JFrog Artifactory"
inputs:
  jfrog-url:
    required: true
  jfrog-username:
    required: true
  jfrog-key:
    required: true
  repo:
    required: true
  file:
    required: true
  target-path:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI (v2.64.0)
      shell: bash
      run: |
        curl -fL https://getcli.jfrog.io | sh
        sudo mv jfrog /usr/local/bin/



    - name: Configure JFrog CLI
      shell: bash
      run: |
        echo "🔧 Configuring JFrog CLI..."
        jf config remove my-server || true
        jf config add my-server \
          --artifactory-url "${{ inputs.jfrog-url }}" \
          --user "${{ inputs.jfrog-username }}" \
          --apikey "${{ inputs.jfrog-key }}" \
          --interactive=false \
          --overwrite \
          --enc-password=false

    - name: Test JFrog Connection
      shell: bash
      run: |
        echo "🔍 Pinging Artifactory..."
        jf rt ping --server-id=my-server
        jf c show my-server

    - name: Upload Artifact
      shell: bash
      run: |
        echo "⬆️ Uploading file: ${{ inputs.file }} → ${{ inputs.repo }}/${{ inputs.target-path }}/"
        jf rt u "${{ inputs.file }}" "${{ inputs.target-path }}" --server-id=my-server
