name: "JFrog Upload Action"
description: "Upload dummy artifact to JFrog Artifactory"
inputs:
  jfrog-url:
    required: true
  jfrog-username:
    required: true
  jfrog-key:
    required: true
  repo:
    required: true
  file:
    required: true
  target-path:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI (v2.64.0)
      shell: bash
      run: |
        curl -fL https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.64.0/jfrog-cli-linux-amd64/jf -o jf
        chmod +x jf
        sudo mv jf /usr/local/bin/
        jf --version



    - name: Configure JFrog CLI
      shell: bash
      run: |
        echo "🔧 Configuring JFrog CLI..."
        jf c show
        jf c remove my-server || true
        jf c add my-server \
          --artifactory-url "${{ inputs.jfrog-url }}" \
          --user "${{ inputs.jfrog-username }}" \
          --password "${{ inputs.jfrog-key }}" \
          --interactive=false \
          --overwrite \
          --basic-auth-only=true

    - name: Test JFrog Connection
      shell: bash
      run: |
        echo "🔍 Pinging Artifactory..."
        jf rt ping --server-id=my-server
        jf c show my-server

    - name: Upload Artifact
      shell: bash
      run: |
        echo "⬆️ Uploading file: ${{ inputs.file }} → ${{ inputs.repo }}/${{ inputs.target-path }}/"
        jf rt u "${{ inputs.file }}" "${{ inputs.target-path }}" --server-id=my-server
