name: "JFrog Upload Action"
description: "Upload dummy artifact to JFrog Artifactory"
inputs:
  jfrog-url:
    required: true
  jfrog-username:
    required: true
  jfrog-key:
    required: true
  #repo:
  #  required: true
  file:
    required: true
  target-path:
    required: true
  #properties-file:
  #  required: false
  #  default: ".jfrog/properties.json"  
  spec-file:
    required: true
  props-file:
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI (v2.64.0)
      shell: bash
      run: |
        if ! command -v jf &> /dev/null; then
          echo "JFrog CLI not found. Installing locally..."
          curl -fL https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.64.0/jfrog-cli-linux-amd64/jf -o ./jf
          chmod +x ./jf
          echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
        else
          echo "JFrog CLI already installed: $(jf --version)"
        fi
    - name: Setup yq
      shell: bash
      run: |
        if ! command -v yq &>/dev/null; then
          echo "Installing yq..."
          curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o yq
          chmod +x yq
          sudo mv yq /usr/local/bin/
        fi
        yq --version
    
    - name: Configure JFrog CLI
      shell: bash
      run: |
        mkdir -p ~/.jfrog
        jf c remove my-server || true
        jf c add my-server \
          --artifactory-url "${{ inputs.jfrog-url }}" \
          --user "${{ inputs.jfrog-username }}"\
          --password "${{ inputs.jfrog-key }}" \
          --basic-auth-only=true \
          --interactive=false \
          --enc-password=false
          
    - name: Read properties from text file
      id: read-props
      shell: bash
      run: |
        FILE=".jfrog/properties.txt"
        echo "Reading properties from $FILE..."
        #PROPS=$(cat "$FILE")
        PROPS=$(envsubst < .jfrog/properties.txt | tr '\n' ';' | sed 's/;$//')
        echo "Generated Props: $PROPS"
        sed "s|\$props|$PROPS|" ${{ inputs.spec-file }} > .jfrog/spec_with_props.json
        
        cat .jfrog/spec_with_props.json  


    - name: Upload file to Artifactory
      shell: bash
      run: |
        jf rt u --spec=".jfrog/spec_with_props.json" --server-id=my-server



