name: "jf Upload Action"
description: "Upload dummy artifact to jf Artifactory"
inputs:
  jf-url:
    description: "jf Artifactory URL"
    required: true
  jf-username:
    description: "jf username"
    required: true
  jf-key:
    description: "jf password or API key"
    required: true
  repo:
    description: "Target repository in Artifactory"
    required: true
  file:
    description: "File to upload"
    required: true
  target-path:
    description: "Path in Artifactory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup jf CLI
      shell: bash
      run: |
        curl -fL https://getcli.jf.io | sh
        sudo mv jf /usr/local/bin/

    - name: Configure jf CLI
      shell: bash
      run: |
        echo "🔑 Configuring jf CLI..."
        jf config add my-server \
          --artifactory-url "${{ inputs.jf-url }}" \
          --user "${{ inputs.jf-username }}" \
          --apikey "${{ inputs.jf-password }}" \
          --interactive=false \
          --overwrite \
          --enc-password=false

   
    - name: Verify jf Connection
      shell: bash
      run: |
        echo "🔍 Checking jf server connectivity..."
        jf rt ping --server-id=my-server
        echo "📜 Showing jf configuration..."
        jf config show my-server
    
    - name: Upload Artifact
      shell: bash
      run: |
        jf rt u "${{ inputs.file }}" "{{ inputs.target-path }}"
