name: "JFrog Upload Action"
description: "Upload dummy artifact to JFrog Artifactory"
inputs:
  jfrog-url:
    required: true
    type: string
  jfrog-username:
    required: true
    type: string
  jfrog-key:
    required: true
    type: string
  repo:
    required: true
    type: string
  file:
    required: true
    type: string
  target-path:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI (v2.64.0)
      shell: bash
      run: |
        curl -fL https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.64.0/jfrog-cli-linux-amd64/jf -o jf
        chmod +x jf
        sudo mv jf /usr/local/bin/
        jf --version

   - name: Upload Artifact
     shell: bash
     run: |
       #echo "⬆️ Uploading file: ${{ inputs.file }} → ${{ inputs.repo }}/${{ inputs.target-path }}/"
       #jf rt u "${{ inputs.file }}" "${{ inputs.target-path }}" --server-id=my-server
       jf rt u "dummy.txt" "toolchains/linux/" --url="http://localhost:7000/artifactory" --user="admin" --password="AKCpBvWUa7JPuuicSK3piDztxKxPUK8jv8w5PzutGVZ8uuVkPGmrDJWvJKvyngcuyUbWtvDqz"

