name: "JFrog Upload Action"
description: "Upload dummy artifact to JFrog Artifactory"
inputs:
  jfrog-url:
    required: true
  jfrog-username:
    required: true
  jfrog-key:
    required: true
  repo:
    required: true
  file:
    required: true
  target-path:
    required: true
  properties-file:
    required: false
    default: ".jfrog/properties.json"  


runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI (v2.64.0)
      shell: bash
      run: |
        if ! command -v jf &> /dev/null; then
          echo "JFrog CLI not found. Installing locally..."
          curl -fL https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.64.0/jfrog-cli-linux-amd64/jf -o ./jf
          chmod +x ./jf
          echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
        else
          echo "JFrog CLI already installed: $(jf --version)"
        fi

    
    - name: Configure JFrog CLI
      shell: bash
      run: |
        mkdir -p ~/.jfrog
        jf c remove my-server || true
        jf c add my-server \
          --artifactory-url "${{ inputs.jfrog-url }}" \
          --user "${{ inputs.jfrog-username }}"\
          --password "${{ inputs.jfrog-key }}" \
          --basic-auth-only=true \
          --interactive=false \
          --enc-password=false
          
    - name: Generate build properties
      shell: bash
      run: |
        echo "Generating build properties..."
        PROPS="build.name=service1"
        PROPS="${PROPS};build.number=${GITHUB_RUN_ID}"
        PROPS="${PROPS};git.branch=${GITHUB_REF_NAME}"
        PROPS="${PROPS};git.commit=${GITHUB_SHA::7}"
        PROPS="${PROPS};version=1.0.0"
        PROPS="${PROPS};ci.url=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        PROPS="${PROPS};ci.workflow=${GITHUB_WORKFLOW}"
        echo "Generated Props: $PROPS"
        echo "props=$PROPS" >> $GITHUB_ENV


    
    - name: Upload file to Artifactory
      shell: bash
      run: |
        jf rt u "${{ inputs.file }}" "${{ inputs.target-path }}" 
          --server-id my-server \
          --props "${{ steps.build-props.outputs.props }}" \
          --build-name $(jq -r '.["build.name"]' ${{ inputs.properties-file }}) \
          --build-number $(jq -r '.["build.number"]' ${{ inputs.properties-file }})
        echo "Upload completed ✅"


