name: "JFrog Upload Action"
description: "Upload dummy artifact to JFrog Artifactory"
inputs:
  jfrog-url:
    required: true
  jfrog-username:
    required: true
  jfrog-key:
    required: true
  #repo:
  #  required: true
  file:
    required: true
  #target-path:
  #  required: true
  #properties-file:
  #  required: false
  #  default: ".jfrog/properties.json"  
  spec-file:
    required: true
  props-file:
    required: true
  build-name:
    required: false
    default: ${{ github.repository }}   # default = repo name
  build-number:
    required: false
    default: ${{ github.run_id }}       # default = GitHub run ID


runs:
  using: "composite"
  steps:
    # - name: Setup JFrog CLI (v2.64.0)
    #   shell: bash
    #   run: |
    #     if ! command -v jf &> /dev/null; then
    #       echo "JFrog CLI not found. Installing locally..."
    #       curl -fL https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.64.0/jfrog-cli-linux-amd64/jf -o ./jf
    #       chmod +x ./jf
    #       echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
    #     else
    #       echo "JFrog CLI already installed: $(jf --version)"
    #     fi
    - name: Setup JFrog CLI (Official Action)
      if: steps.check-cli.outputs.install == 'true'
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 2.64.0
        
    - name: Configure JFrog CLI
      shell: bash
      run: |
        mkdir -p ~/.jfrog
        jf c remove my-server || true
        jf c add my-server \
          --artifactory-url "${{ inputs.jfrog-url }}" \
          --user "${{ inputs.jfrog-username }}"\
          --password "${{ inputs.jfrog-key }}" \
          --basic-auth-only=true \
          --interactive=false \
          --enc-password=false
          
    - name: Read properties from text file
      id: read-props
      shell: bash
      run: |
        #FILE=".jfrog/properties.txt"
        echo "Reading properties from $FILE..."
        #PROPS=$(cat "$FILE")
        PROPS=$(envsubst < ${{ inputs.props-file }} | tr '\n' ';' | sed 's/;$//')
        echo "Generated Props: $PROPS"
        sed "s|\$props|$PROPS|" ${{ inputs.spec-file }} > .jfrog/spec_with_props.json
        
        cat .jfrog/spec_with_props.json  


    - name: Upload file to Artifactory
      shell: bash
      run: |
        jf rt u --spec=".jfrog/spec_with_props.json" --server-id=my-server


    - name: Stage Build Metadata
      shell: bash
      run: |
        BUILD_NAME="my-build"
        BUILD_NUMBER=$GITHUB_RUN_ID
    
        jf rt bag --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER \
          --module="module1" \
          --prop="build.name=service1" \
          --prop="git.branch=$GITHUB_REF_NAME" \
          --prop="git.commit=$GITHUB_SHA" \
          --prop="version=1.0.0" \
          --prop="ci.workflow=$GITHUB_WORKFLOW" \
          --prop="ci.url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
    
    - name: Publish Build
      shell: bash
      run: |
        jf bp $BUILD_NAME $BUILD_NUMBER
