name: "JFrog Upload Action"
description: "Upload dummy artifact to JFrog Artifactory"
inputs:
  jfrog-url:
    required: true
  jfrog-username:
    required: true
  jfrog-key:
    required: true
  repo:
    required: true
  file:
    required: true
  target-path:
    required: true
  properties-file:
    required: false
    default: ".json/properties.json"  


runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI (v2.64.0)
      shell: bash
      run: |
        if ! command -v jf &> /dev/null; then
          echo "JFrog CLI not found. Installing locally..."
          curl -fL https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.64.0/jfrog-cli-linux-amd64/jf -o ./jf
          chmod +x ./jf
          echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
        else
          echo "JFrog CLI already installed: $(jf --version)"
        fi

    
    - name: Configure JFrog CLI
      shell: bash
      run: |
        mkdir -p ~/.jfrog
        jf c remove my-server || true
        jf c add my-server \
          --artifactory-url "${{ inputs.jfrog-url }}" \
          --user "${{ inputs.jfrog-username }}"\
          --password "${{ inputs.jfrog-key }}" \
          --basic-auth-only=true \
          --interactive=false \
          --enc-password=false
    - name: Prepare Properties
      id: build-props
      shell: bash
      run: |
        echo "Reading properties from ${{ inputs.properties-file }}..."
        PROPS=$(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | join(";")' ${{ inputs.properties-file }})
        echo "Generated Props: $PROPS"
        echo "props=$PROPS" >> $GITHUB_OUTPUT
    
    - name: Upload file to Artifactory
      shell: bash
      run: |
        jf rt u "${{ inputs.file }}" "${{ inputs.target-path }}" 
          --server-id my-server \
          --props "${{ steps.build-props.outputs.props }}" \
          --build-name $(jq -r '.["build.name"]' ${{ inputs.properties-file }}) \
          --build-number $(jq -r '.["build.number"]' ${{ inputs.properties-file }})
        echo "Upload completed ✅"


