name: Run CodiumAI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CodiumAI Action
        uses: codium-ai/codium-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: "app.py"  # Target file
          language: "python"
          output: "test_results.json"  # Save results for analysis

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: codiumai-test-results
          path: test_results.json

