name: Upload Dummy Artifact

on:
  workflow_dispatch:

jobs:
  upload_jfrog:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Dummy File
        run: echo "Hello from GitHub Actions at $(date)" > dummy.txt

      - name: Upload to JFrog
        uses: ./.github/actions/jfrog-upload
        #uses: bhushanvelis/actions/jfrog-upload@v1
        with:
          jfrog-url: ${{ secrets.JFROG_URL }}
          jfrog-username: ${{ secrets.JFROG_USERNAME }}
          jfrog-key: ${{ secrets.JFROG_KEY }}
          file: dummy.txt
          #repo: dummy-repo-local
          target-path: "toolchains/linux/dummy5.txt"
          #properties-file: ".jfrog/properties.json"
          #spec-file: .jfrog/spec.yml
          spec-file: .jfrog/spec.json
          props-file: .jfrog/properties.yml
